### ISSUE TITLE
运行你这程序识别赢字幕时间长吗

### ISSUE THREAD

**Issue by yaojingzhe** [m986883511/extract-video-subtittle#1]
YaoFANGUK的video-subtitle-extractor，识别率非常非常高，但就是耗时太长，1小时的视频，基本是5倍时间。请问作者，你这程序，生成srt字幕，花费的时间是视频的多少倍？非常感谢你的回复。

**Comment by m986883511** [comment]
> YaoFANGUK的video-subtitle-extractor，识别率非常非常高，但就是耗时太长，1小时的视频，基本是5倍时间。请问作者，你这程序，生成srt字幕，花费的时间是视频的多少倍？非常感谢你的回复。

我的程序里面的识别模型就是他的，具体识别时间是不好估算的，这和有没有使用GPU，CPU强不强有关系。
我这个只是CPU版本。
你可以看下我的识别原理，比原作者减少80%的识别次数。
如果视频字幕很少，就是没咋说话，识别次数更少，时间会连一倍不到。
