### ISSUE TITLE
项目咨询

### ISSUE THREAD

**Issue by YeDaxia** [m986883511/extract-video-subtittle#3]
Hello，我尝试了一下这个软件，感觉还是不错的，不过在实际使用中还是会有不少问题。

我是一个独立开发者，这边愿意付费或者合作来完善一下，让这个项目更具实用性，不知道你有没有兴趣呢?

没有找到联系方式，只好通过issue来试一下，你可以在看到之后删除，谢谢。

我的邮箱是yedaxia#foxmail.com

**Comment by m986883511** [comment]
我关闭了哈
