### ISSUE TITLE
提取人声一直没结果

### ISSUE THREAD

**Issue by royzengyi** [m986883511/extract-video-subtittle#5]
![image](https://user-images.githubusercontent.com/47094585/144962101-8f2c77b9-776e-4949-9560-0f0f5e3a5470.png)
视频是40多分钟的连续剧。CPU版本。之前用YaoFANGUK/video-subtitle-extractor提取字幕很成功也准确，但时间比较长。看到作者用音频分析减少了识别的帧数，所以试了一下。但在提取人声时，已经等待了近50分钟没有结果。而且CPU的占用只有1%左右，这明显不正常。用YaoFANGUK/video-subtitle-extractor整个的耗时可能都没有这么久。另外autosub也是提取音频来语音识别字幕，识别人声也很快，同样的视频几分钟就完了。麻烦作者看看是出了什么问题呢。

**Comment by m986883511** [comment]
spleeter使用cpu提取时，因工程量较大，可能会遇到假死情况；并且spleeter最大只能提取十分钟，也就是40分钟他只提取前十分钟；建议不要使用cpu来搞。
使用这两个容器，他们都是gpu版本，在win11上是能直接部署的。这里的spleeter可以提取40分钟，我做了切分，40分钟的视频大概1分钟提取完。
但是这两个容器使用了新的接口，我还在开发。你可以直接访问容器的端口，可以看到接口描述。
docker pull m986883511/ocr:paddle
docker pull m986883511/spleeter:api

**Comment by royzengyi** [comment]
好的，谢谢
